using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace StockDataProject
{
    public class Constants 
    {
        public const string BASE_URL = "https://query1.finance.yahoo.com";

        public static Dictionary<string, string> GetRanges() {
            Dictionary<string, string> keys = new Dictionary<string, string>();
            keys.Add("Daily", "1d");
            keys.Add("Weekly", "1wk");
            keys.Add("Monthly", "1mo");
            return keys;
        }

        public static List<string> GetPatterns()
        {
            List<string> keys = new List<string>()
            {
                "None", "Neutral Doji", "Long-legged Doji", "Gravestone Doji", "Dragonfly Doji", "Bullish Marubozu", "Bearish Marubozu", "Bullish Harami", "Bearish Harami"
            };
            return keys;
        }

        public static Dictionary<string, string> GetTickers()
        {
            Dictionary<string, string> keys = new Dictionary<string, string>();
            keys.Add("MMM", "3M");
            keys.Add("AOS", "A. O. Smith");
            keys.Add("ABT", "Abbott Laboratories");
            keys.Add("ABBV", "AbbVie");
            keys.Add("ABMD", "Abiomed");
            keys.Add("ACN", "Accenture");
            keys.Add("ATVI", "Activision Blizzard");
            keys.Add("ADM", "ADM");
            keys.Add("ADBE", "Adobe");
            keys.Add("AAP", "Advance Auto Parts");
            keys.Add("AMD", "Advanced Micro Devices");
            keys.Add("AES", "AES Corp");
            keys.Add("AFL", "Aflac");
            keys.Add("A", "Agilent Technologies");
            keys.Add("APD", "Air Products & Chemicals");
            keys.Add("AKAM", "Akamai Technologies");
            keys.Add("ALK", "Alaska Air Group");
            keys.Add("ALB", "Albemarle Corporation");
            keys.Add("ARE", "Alexandria Real Estate Equities");
            keys.Add("ALGN", "Align Technology");
            keys.Add("ALLE", "Allegion");
            keys.Add("LNT", "Alliant Energy");
            keys.Add("ALL", "Allstate Corp");
            keys.Add("GOOGL", "Alphabet (Class A)");
            keys.Add("GOOG", "Alphabet (Class C)");
            keys.Add("MO", "Altria Group");
            keys.Add("AMZN", "Amazon");
            keys.Add("AMCR", "Amcor");
            keys.Add("AEE", "Ameren Corp");
            keys.Add("AAL", "American Airlines Group");
            keys.Add("AEP", "American Electric Power");
            keys.Add("AXP", "American Express");
            keys.Add("AIG", "American International Group");
            keys.Add("AMT", "American Tower");
            keys.Add("AWK", "American Water Works");
            keys.Add("AMP", "Ameriprise Financial");
            keys.Add("ABC", "AmerisourceBergen");
            keys.Add("AME", "Ametek");
            keys.Add("AMGN", "Amgen");
            keys.Add("APH", "Amphenol");
            keys.Add("ADI", "Analog Devices");
            keys.Add("ANSS", "Ansys");
            keys.Add("ANTM", "Anthem");
            keys.Add("AON", "Aon");
            keys.Add("APA", "APA Corporation");
            keys.Add("AAPL", "Apple");
            keys.Add("AMAT", "Applied Materials");
            keys.Add("APTV", "Aptiv");
            keys.Add("ANET", "Arista Networks");
            keys.Add("AJG", "Arthur J. Gallagher & Co.");
            keys.Add("AIZ", "Assurant");
            keys.Add("T", "AT&T");
            keys.Add("ATO", "Atmos Energy");
            keys.Add("ADSK", "Autodesk");
            keys.Add("ADP", "Automatic Data Processing");
            keys.Add("AZO", "AutoZone");
            keys.Add("AVB", "AvalonBay Communities");
            keys.Add("AVY", "Avery Dennison");
            keys.Add("BKR", "Baker Hughes");
            keys.Add("BLL", "Ball Corp");
            keys.Add("BAC", "Bank of America");
            keys.Add("BBWI", "Bath & Body Works Inc.");
            keys.Add("BAX", "Baxter International");
            keys.Add("BDX", "Becton Dickinson");
            keys.Add("BRK.B", "Berkshire Hathaway");
            keys.Add("BBY", "Best Buy");
            keys.Add("BIO", "Bio-Rad Laboratories");
            keys.Add("TECH", "Bio-Techne");
            keys.Add("BIIB", "Biogen");
            keys.Add("BLK", "BlackRock");
            keys.Add("BK", "BNY Mellon");
            keys.Add("BA", "Boeing");
            keys.Add("BKNG", "Booking Holdings");
            keys.Add("BWA", "BorgWarner");
            keys.Add("BXP", "Boston Properties");
            keys.Add("BSX", "Boston Scientific");
            keys.Add("BMY", "Bristol Myers Squibb");
            keys.Add("AVGO", "Broadcom");
            keys.Add("BR", "Broadridge Financial Solutions");
            keys.Add("BRO", "Brown & Brown");
            keys.Add("BF.B", "Brownâ€“Forman");
            keys.Add("CHRW", "C. H. Robinson");
            keys.Add("CDNS", "Cadence Design Systems");
            keys.Add("CZR", "Caesars Entertainment");
            keys.Add("CPB", "Campbell Soup");
            keys.Add("COF", "Capital One Financial");
            keys.Add("CAH", "Cardinal Health");
            keys.Add("KMX", "CarMax");
            keys.Add("CCL", "Carnival Corporation");
            keys.Add("CARR", "Carrier Global");
            keys.Add("CTLT", "Catalent");
            keys.Add("CAT", "Caterpillar");
            keys.Add("CBOE", "Cboe Global Markets");
            keys.Add("CBRE", "CBRE");
            keys.Add("CDW", "CDW");
            keys.Add("CE", "Celanese");
            keys.Add("CNC", "Centene Corporation");
            keys.Add("CNP", "CenterPoint Energy");
            keys.Add("CDAY", "Ceridian");
            keys.Add("CERN", "Cerner");
            keys.Add("CF", "CF Industries");
            keys.Add("CRL", "Charles River Laboratories");
            keys.Add("SCHW", "Charles Schwab Corporation");
            keys.Add("CHTR", "Charter Communications");
            keys.Add("CVX", "Chevron Corporation");
            keys.Add("CMG", "Chipotle Mexican Grill");
            keys.Add("CB", "Chubb");
            keys.Add("CHD", "Church & Dwight");
            keys.Add("CI", "Cigna");
            keys.Add("CINF", "Cincinnati Financial");
            keys.Add("CTAS", "Cintas Corporation");
            keys.Add("CSCO", "Cisco Systems");
            keys.Add("C", "Citigroup");
            keys.Add("CFG", "Citizens Financial Group");
            keys.Add("CTXS", "Citrix Systems");
            keys.Add("CLX", "Clorox");
            keys.Add("CME", "CME Group");
            keys.Add("CMS", "CMS Energy");
            keys.Add("KO", "Coca-Cola Company");
            keys.Add("CTSH", "Cognizant Technology Solutions");
            keys.Add("CL", "Colgate-Palmolive");
            keys.Add("CMCSA", "Comcast");
            keys.Add("CMA", "Comerica");
            keys.Add("CAG", "Conagra Brands");
            keys.Add("COP", "ConocoPhillips");
            keys.Add("ED", "Consolidated Edison");
            keys.Add("STZ", "Constellation Brands");
            keys.Add("CPRT", "Copart");
            keys.Add("GLW", "Corning");
            keys.Add("CTVA", "Corteva");
            keys.Add("COST", "Costco");
            keys.Add("CTRA", "Coterra");
            keys.Add("CCI", "Crown Castle");
            keys.Add("CSX", "CSX");
            keys.Add("CMI", "Cummins");
            keys.Add("CVS", "CVS Health");
            keys.Add("DHI", "D. R. Horton");
            keys.Add("DHR", "Danaher Corporation");
            keys.Add("DRI", "Darden Restaurants");
            keys.Add("DVA", "DaVita");
            keys.Add("DE", "Deere & Co.");
            keys.Add("DAL", "Delta Air Lines");
            keys.Add("XRAY", "Dentsply Sirona");
            keys.Add("DVN", "Devon Energy");
            keys.Add("DXCM", "DexCom");
            keys.Add("FANG", "Diamondback Energy");
            keys.Add("DLR", "Digital Realty Trust");
            keys.Add("DFS", "Discover Financial Services");
            keys.Add("DISCA", "Discovery (Series A)");
            keys.Add("DISCK", "Discovery (Series C)");
            keys.Add("DISH", "Dish Network");
            keys.Add("DG", "Dollar General");
            keys.Add("DLTR", "Dollar Tree");
            keys.Add("D", "Dominion Energy");
            keys.Add("DPZ", "Domino's Pizza");
            keys.Add("DOV", "Dover Corporation");
            keys.Add("DOW", "Dow");
            keys.Add("DTE", "DTE Energy");
            keys.Add("DUK", "Duke Energy");
            keys.Add("DRE", "Duke Realty Corp");
            keys.Add("DD", "DuPont");
            keys.Add("DXC", "DXC Technology");
            keys.Add("EMN", "Eastman Chemical");
            keys.Add("ETN", "Eaton Corporation");
            keys.Add("EBAY", "eBay");
            keys.Add("ECL", "Ecolab");
            keys.Add("EIX", "Edison International");
            keys.Add("EW", "Edwards Lifesciences");
            keys.Add("EA", "Electronic Arts");
            keys.Add("LLY", "Eli Lilly & Co");
            keys.Add("EMR", "Emerson Electric Company");
            keys.Add("ENPH", "Enphase Energy");
            keys.Add("ETR", "Entergy");
            keys.Add("EOG", "EOG Resources");
            keys.Add("EFX", "Equifax");
            keys.Add("EQIX", "Equinix");
            keys.Add("EQR", "Equity Residential");
            keys.Add("ESS", "Essex Property Trust");
            keys.Add("EL", "EstÃ©e Lauder Companies");
            keys.Add("ETSY", "Etsy");
            keys.Add("RE", "Everest Re");
            keys.Add("EVRG", "Evergy");
            keys.Add("ES", "Eversource Energy");
            keys.Add("EXC", "Exelon");
            keys.Add("EXPE", "Expedia Group");
            keys.Add("EXPD", "Expeditors");
            keys.Add("EXR", "Extra Space Storage");
            keys.Add("XOM", "ExxonMobil");
            keys.Add("FFIV", "F5 Networks");
            keys.Add("FB", "Facebook");
            keys.Add("FAST", "Fastenal");
            keys.Add("FRT", "Federal Realty Investment Trust");
            keys.Add("FDX", "FedEx");
            keys.Add("FIS", "Fidelity National Information Services");
            keys.Add("FITB", "Fifth Third Bancorp");
            keys.Add("FRC", "First Republic Bank");
            keys.Add("FE", "FirstEnergy");
            keys.Add("FISV", "Fiserv");
            keys.Add("FLT", "Fleetcor");
            keys.Add("FMC", "FMC Corporation");
            keys.Add("F", "Ford");
            keys.Add("FTNT", "Fortinet");
            keys.Add("FTV", "Fortive");
            keys.Add("FBHS", "Fortune Brands Home & Security");
            keys.Add("FOXA", "Fox Corporation (Class A)");
            keys.Add("FOX", "Fox Corporation (Class B)");
            keys.Add("BEN", "Franklin Resources");
            keys.Add("FCX", "Freeport-McMoRan");
            keys.Add("GPS", "Gap");
            keys.Add("GRMN", "Garmin");
            keys.Add("IT", "Gartner");
            keys.Add("GNRC", "Generac Holdings");
            keys.Add("GD", "General Dynamics");
            keys.Add("GE", "General Electric");
            keys.Add("GIS", "General Mills");
            keys.Add("GM", "General Motors");
            keys.Add("GPC", "Genuine Parts");
            keys.Add("GILD", "Gilead Sciences");
            keys.Add("GPN", "Global Payments");
            keys.Add("GL", "Globe Life");
            keys.Add("GS", "Goldman Sachs");
            keys.Add("HAL", "Halliburton");
            keys.Add("HBI", "Hanesbrands");
            keys.Add("HAS", "Hasbro");
            keys.Add("HCA", "HCA Healthcare");
            keys.Add("PEAK", "Healthpeak Properties");
            keys.Add("HSIC", "Henry Schein");
            keys.Add("HES", "Hess Corporation");
            keys.Add("HPE", "Hewlett Packard Enterprise");
            keys.Add("HLT", "Hilton Worldwide");
            keys.Add("HOLX", "Hologic");
            keys.Add("HD", "Home Depot");
            keys.Add("HON", "Honeywell");
            keys.Add("HRL", "Hormel");
            keys.Add("HST", "Host Hotels & Resorts");
            keys.Add("HWM", "Howmet Aerospace");
            keys.Add("HPQ", "HP");
            keys.Add("HUM", "Humana");
            keys.Add("HBAN", "Huntington Bancshares");
            keys.Add("HII", "Huntington Ingalls Industries");
            keys.Add("IBM", "IBM");
            keys.Add("IEX", "IDEX Corporation");
            keys.Add("IDXX", "Idexx Laboratories");
            keys.Add("INFO", "IHS Markit");
            keys.Add("ITW", "Illinois Tool Works");
            keys.Add("ILMN", "Illumina");
            keys.Add("INCY", "Incyte");
            keys.Add("IR", "Ingersoll Rand");
            keys.Add("INTC", "Intel");
            keys.Add("ICE", "Intercontinental Exchange");
            keys.Add("IFF", "International Flavors & Fragrances");
            keys.Add("IP", "International Paper");
            keys.Add("IPG", "Interpublic Group");
            keys.Add("INTU", "Intuit");
            keys.Add("ISRG", "Intuitive Surgical");
            keys.Add("IVZ", "Invesco");
            keys.Add("IPGP", "IPG Photonics");
            keys.Add("IQV", "IQVIA");
            keys.Add("IRM", "Iron Mountain");
            keys.Add("JBHT", "J. B. Hunt");
            keys.Add("JKHY", "Jack Henry & Associates");
            keys.Add("J", "Jacobs Engineering Group");
            keys.Add("SJM", "JM Smucker");
            keys.Add("JNJ", "Johnson & Johnson");
            keys.Add("JCI", "Johnson Controls");
            keys.Add("JPM", "JPMorgan Chase");
            keys.Add("JNPR", "Juniper Networks");
            keys.Add("KSU", "Kansas City Southern");
            keys.Add("K", "Kellogg's");
            keys.Add("KEY", "KeyCorp");
            keys.Add("KEYS", "Keysight Technologies");
            keys.Add("KMB", "Kimberly-Clark");
            keys.Add("KIM", "Kimco Realty");
            keys.Add("KMI", "Kinder Morgan");
            keys.Add("KLAC", "KLA Corporation");
            keys.Add("KHC", "Kraft Heinz");
            keys.Add("KR", "Kroger");
            keys.Add("LHX", "L3Harris Technologies");
            keys.Add("LH", "LabCorp");
            keys.Add("LRCX", "Lam Research");
            keys.Add("LW", "Lamb Weston");
            keys.Add("LVS", "Las Vegas Sands");
            keys.Add("LEG", "Leggett & Platt");
            keys.Add("LDOS", "Leidos");
            keys.Add("LEN", "Lennar");
            keys.Add("LNC", "Lincoln National");
            keys.Add("LIN", "Linde");
            keys.Add("LYV", "Live Nation Entertainment");
            keys.Add("LKQ", "LKQ Corporation");
            keys.Add("LMT", "Lockheed Martin");
            keys.Add("L", "Loews Corporation");
            keys.Add("LOW", "Lowe's");
            keys.Add("LUMN", "Lumen Technologies");
            keys.Add("LYB", "LyondellBasell");
            keys.Add("MTB", "M&T Bank");
            keys.Add("MRO", "Marathon Oil");
            keys.Add("MPC", "Marathon Petroleum");
            keys.Add("MKTX", "MarketAxess");
            keys.Add("MAR", "Marriott International");
            keys.Add("MMC", "Marsh & McLennan");
            keys.Add("MLM", "Martin Marietta Materials");
            keys.Add("MAS", "Masco");
            keys.Add("MA", "Mastercard");
            keys.Add("MTCH", "Match Group");
            keys.Add("MKC", "McCormick & Company");
            keys.Add("MCD", "McDonald's");
            keys.Add("MCK", "McKesson Corporation");
            keys.Add("MDT", "Medtronic");
            keys.Add("MRK", "Merck & Co.");
            keys.Add("MET", "MetLife");
            keys.Add("MTD", "Mettler Toledo");
            keys.Add("MGM", "MGM Resorts International");
            keys.Add("MCHP", "Microchip Technology");
            keys.Add("MU", "Micron Technology");
            keys.Add("MSFT", "Microsoft");
            keys.Add("MAA", "Mid-America Apartments");
            keys.Add("MRNA", "Moderna");
            keys.Add("MHK", "Mohawk Industries");
            keys.Add("TAP", "Molson Coors Beverage Company");
            keys.Add("MDLZ", "Mondelez International");
            keys.Add("MPWR", "Monolithic Power Systems");
            keys.Add("MNST", "Monster Beverage");
            keys.Add("MCO", "Moody's Corporation");
            keys.Add("MS", "Morgan Stanley");
            keys.Add("MSI", "Motorola Solutions");
            keys.Add("MSCI", "MSCI");
            keys.Add("NDAQ", "Nasdaq");
            keys.Add("NTAP", "NetApp");
            keys.Add("NFLX", "Netflix");
            keys.Add("NWL", "Newell Brands");
            keys.Add("NEM", "Newmont");
            keys.Add("NWSA", "News Corp (Class A)");
            keys.Add("NWS", "News Corp (Class B)");
            keys.Add("NEE", "NextEra Energy");
            keys.Add("NLSN", "Nielsen Holdings");
            keys.Add("NKE", "Nike");
            keys.Add("NI", "NiSource");
            keys.Add("NSC", "Norfolk Southern");
            keys.Add("NTRS", "Northern Trust");
            keys.Add("NOC", "Northrop Grumman");
            keys.Add("NLOK", "NortonLifeLock");
            keys.Add("NCLH", "Norwegian Cruise Line Holdings");
            keys.Add("NRG", "NRG Energy");
            keys.Add("NUE", "Nucor");
            keys.Add("NVDA", "Nvidia");
            keys.Add("NVR", "NVR");
            keys.Add("NXPI", "NXP");
            keys.Add("ORLY", "O'Reilly Automotive");
            keys.Add("OXY", "Occidental Petroleum");
            keys.Add("ODFL", "Old Dominion Freight Line");
            keys.Add("OMC", "Omnicom Group");
            keys.Add("OKE", "Oneok");
            keys.Add("ORCL", "Oracle");
            keys.Add("OGN", "Organon & Co.");
            keys.Add("OTIS", "Otis Worldwide");
            keys.Add("PCAR", "Paccar");
            keys.Add("PKG", "Packaging Corporation of America");
            keys.Add("PH", "Parker-Hannifin");
            keys.Add("PAYX", "Paychex");
            keys.Add("PAYC", "Paycom");
            keys.Add("PYPL", "PayPal");
            keys.Add("PENN", "Penn National Gaming");
            keys.Add("PNR", "Pentair");
            keys.Add("PBCT", "People's United Financial");
            keys.Add("PEP", "PepsiCo");
            keys.Add("PKI", "PerkinElmer");
            keys.Add("PFE", "Pfizer");
            keys.Add("PM", "Philip Morris International");
            keys.Add("PSX", "Phillips 66");
            keys.Add("PNW", "Pinnacle West Capital");
            keys.Add("PXD", "Pioneer Natural Resources");
            keys.Add("PNC", "PNC Financial Services");
            keys.Add("POOL", "Pool Corporation");
            keys.Add("PPG", "PPG Industries");
            keys.Add("PPL", "PPL");
            keys.Add("PFG", "Principal Financial Group");
            keys.Add("PG", "Procter & Gamble");
            keys.Add("PGR", "Progressive Corporation");
            keys.Add("PLD", "Prologis");
            keys.Add("PRU", "Prudential Financial");
            keys.Add("PTC", "PTC");
            keys.Add("PEG", "Public Service Enterprise Group");
            keys.Add("PSA", "Public Storage");
            keys.Add("PHM", "PulteGroup");
            keys.Add("PVH", "PVH");
            keys.Add("QRVO", "Qorvo");
            keys.Add("QCOM", "Qualcomm");
            keys.Add("PWR", "Quanta Services");
            keys.Add("DGX", "Quest Diagnostics");
            keys.Add("RL", "Ralph Lauren Corporation");
            keys.Add("RJF", "Raymond James Financial");
            keys.Add("RTX", "Raytheon Technologies");
            keys.Add("O", "Realty Income Corporation");
            keys.Add("REG", "Regency Centers");
            keys.Add("REGN", "Regeneron Pharmaceuticals");
            keys.Add("RF", "Regions Financial Corporation");
            keys.Add("RSG", "Republic Services");
            keys.Add("RMD", "ResMed");
            keys.Add("RHI", "Robert Half International");
            keys.Add("ROK", "Rockwell Automation");
            keys.Add("ROL", "Rollins");
            keys.Add("ROP", "Roper Technologies");
            keys.Add("ROST", "Ross Stores");
            keys.Add("RCL", "Royal Caribbean Group");
            keys.Add("SPGI", "S&P Global");
            keys.Add("CRM", "Salesforce");
            keys.Add("SBAC", "SBA Communications");
            keys.Add("SLB", "Schlumberger");
            keys.Add("STX", "Seagate Technology");
            keys.Add("SEE", "Sealed Air");
            keys.Add("SRE", "Sempra Energy");
            keys.Add("NOW", "ServiceNow");
            keys.Add("SHW", "Sherwin-Williams");
            keys.Add("SPG", "Simon Property Group");
            keys.Add("SWKS", "Skyworks Solutions");
            keys.Add("SNA", "Snap-on");
            keys.Add("SO", "Southern Company");
            keys.Add("LUV", "Southwest Airlines");
            keys.Add("SWK", "Stanley Black & Decker");
            keys.Add("SBUX", "Starbucks");
            keys.Add("STT", "State Street Corporation");
            keys.Add("STE", "Steris");
            keys.Add("SYK", "Stryker Corporation");
            keys.Add("SIVB", "SVB Financial");
            keys.Add("SYF", "Synchrony Financial");
            keys.Add("SNPS", "Synopsys");
            keys.Add("SYY", "Sysco");
            keys.Add("TMUS", "T-Mobile US");
            keys.Add("TROW", "T. Rowe Price");
            keys.Add("TTWO", "Take-Two Interactive");
            keys.Add("TPR", "Tapestry");
            keys.Add("TGT", "Target Corporation");
            keys.Add("TEL", "TE Connectivity");
            keys.Add("TDY", "Teledyne Technologies");
            keys.Add("TFX", "Teleflex");
            keys.Add("TER", "Teradyne");
            keys.Add("TSLA", "Tesla");
            keys.Add("TXN", "Texas Instruments");
            keys.Add("TXT", "Textron");
            keys.Add("COO", "The Cooper Companies");
            keys.Add("HIG", "The Hartford");
            keys.Add("HSY", "The Hershey Company");
            keys.Add("MOS", "The Mosaic Company");
            keys.Add("TRV", "The Travelers Companies");
            keys.Add("DIS", "The Walt Disney Company");
            keys.Add("TMO", "Thermo Fisher Scientific");
            keys.Add("TJX", "TJX Companies");
            keys.Add("TSCO", "Tractor Supply Company");
            keys.Add("TT", "Trane Technologies");
            keys.Add("TDG", "TransDigm Group");
            keys.Add("TRMB", "Trimble");
            keys.Add("TFC", "Truist Financial");
            keys.Add("TWTR", "Twitter");
            keys.Add("TYL", "Tyler Technologies");
            keys.Add("TSN", "Tyson Foods");
            keys.Add("USB", "U.S. Bancorp");
            keys.Add("UDR", "UDR");
            keys.Add("ULTA", "Ulta Beauty");
            keys.Add("UAA", "Under Armour (Class A)");
            keys.Add("UA", "Under Armour (Class C)");
            keys.Add("UNP", "Union Pacific");
            keys.Add("UAL", "United Airlines");
            keys.Add("UPS", "United Parcel Service");
            keys.Add("URI", "United Rentals");
            keys.Add("UNH", "UnitedHealth Group");
            keys.Add("UHS", "Universal Health Services");
            keys.Add("VLO", "Valero Energy");
            keys.Add("VTR", "Ventas");
            keys.Add("VRSN", "Verisign");
            keys.Add("VRSK", "Verisk Analytics");
            keys.Add("VZ", "Verizon Communications");
            keys.Add("VRTX", "Vertex Pharmaceuticals");
            keys.Add("VFC", "VF Corporation");
            keys.Add("VIAC", "ViacomCBS");
            keys.Add("VTRS", "Viatris");
            keys.Add("V", "Visa");
            keys.Add("VNO", "Vornado Realty Trust");
            keys.Add("VMC", "Vulcan Materials");
            keys.Add("WRB", "W. R. Berkley Corporation");
            keys.Add("GWW", "W. W. Grainger");
            keys.Add("WAB", "Wabtec");
            keys.Add("WBA", "Walgreens Boots Alliance");
            keys.Add("WMT", "Walmart");
            keys.Add("WM", "Waste Management");
            keys.Add("WAT", "Waters Corporation");
            keys.Add("WEC", "WEC Energy Group");
            keys.Add("WFC", "Wells Fargo");
            keys.Add("WELL", "Welltower");
            keys.Add("WST", "West Pharmaceutical Services");
            keys.Add("WDC", "Western Digital");
            keys.Add("WU", "Western Union");
            keys.Add("WRK", "WestRock");
            keys.Add("WY", "Weyerhaeuser");
            keys.Add("WHR", "Whirlpool Corporation");
            keys.Add("WMB", "Williams Companies");
            keys.Add("WLTW", "Willis Towers Watson");
            keys.Add("WYNN", "Wynn Resorts");
            keys.Add("XEL", "Xcel Energy");
            keys.Add("XLNX", "Xilinx");
            keys.Add("XYL", "Xylem");
            keys.Add("YUM", "Yum! Brands");
            keys.Add("ZBRA", "Zebra Technologies");
            keys.Add("ZBH", "Zimmer Biomet");
            keys.Add("ZION", "Zions Bancorp");
            keys.Add("ZTS", "Zoetis");
            return keys.OrderBy(x => x.Key).ToDictionary(x => x.Key, x => x.Value);
        }
    }
}
